name: Build Sample for Android

on: push

jobs:
  apk:
    name: Apk Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Clone the repos and copy the android-project
        run:  |
               git clone https://github.com/Ravbug/sdl3-sample.git
               git clone https://github.com/captain1947/sdl3-sample-android-project.git
               cp -r sdl3-sample-android-project/android-project sdl3-sample/

      - name: Build the APK
        run: |
              ls sdl3-sample
              cd ./sdl3-sample/android-project/app
              ./gradlew assembleDebug

      - name: Upload the APK
        uses: actions/upload-artifact@v3
        with: 
          name: artifact
          path: SDL/android-project/app/build/outputs/apk/debug/app-debug.apk
