name: Build Sample for Android

on: push

jobs:
  apk:
    name: Apk Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build the APK
        run: |
              export JAVA_HOME=$JAVA_HOME_17_X64
              cd android-project/
              chmod +x ./gradlew
              ./gradlew assembleDebug

      - name: Upload the APK
        uses: actions/upload-artifact@v3
        with: 
          name: artifact
          path: android-project/app/build/outputs/apk/debug/app-debug.apk
