name: Build Sample for Android

on: push

jobs:
  apk:
    name: Apk Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repos and copy the android-project
        run:  |
               git clone https://github.com/Ravbug/sdl3-sample.git --depth=1 --recurse-submodules
               git clone https://github.com/captain1947/sdl3-sample-android-project.git
               cp -r sdl3-sample-android-project/android-project sdl3-sample/

      - name: Build the APK
        run: |
              export JAVA_HOME=$JAVA_HOME_17_X64
              cd sdl3-sample/android-project
              chmod +x gradlew
              ./gradlew assembleDebug

      - name: Upload the APK
        uses: actions/upload-artifact@v3
        with: 
          name: artifact
          path: android-project/app/build/outputs/apk/debug/app-debug.apk
